exclude:
- README.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

gems:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji

paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: YaManicKill # jekyll-seo-tag > Owners twitter username
author: YaManicKill # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Alistair McKinlay # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/YaManicKill
    - https://www.facebook.com/yamanickill
    - https://www.linkedin.com/in/alistair-mckinlay
    - https://github.com/yamanickill

sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://unsplash.it/1300/400?image=1067"

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

encoding: utf-8 # Make sure the encoding is right
title: "YaManicKill" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/placeholder-logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Musings from a nerd" # Site description and default description, also used in jekyll-seo-tag
url: "https://www.10people.co.uk" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/yamanickill/10people"
email: "blog@10people.co.uk"
disqus: "alembic-1"
avatarurl: "https://en.gravatar.com/userimage/4980373/ea450b7d082dce05e06a3052d53bc51a.png"

# 8. Site navigation
navigation_header:
  Home: /
  10People: /10people
  Alistotle: /alistotle

navigation_footer:
  Theme by David Darnes: https://darn.es

social_links:
  Twitter: https://twitter.com/YaManicKill
  LinkedIn: https://www.linkedin.com/in/alistair-mckinlay
  GitHub: https://github.com/yamanickill
